#!/bin/bash

set -e

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
cd $SCRIPTPATH
TIMESTAMP=$(date "+%Y%m%d%H%M%S")
XMLFile="../PluginsAndFeatures/azure-toolkit-for-intellij/src/main/resources/META-INF/plugin.xml"

git checkout -- $XMLFile
javac XMLHelper.java
java XMLHelper $XMLFile '//idea-plugin/version/text()' "-${1}-${TIMESTAMP}" "JOIN" "true"